plugins {
    id 'java-gradle-plugin'
    id 'com.gradle.plugin-publish' version '2.1.1'
}

group = 'io.github.Akfz'
version = '1.0.0'

repositories {
    mavenCentral()
}

java {
    sourceCompatibility = JavaVersion.VERSION_17
    targetCompatibility = JavaVersion.VERSION_17
}

gradlePlugin {
    website = 'https://github.com/Akfz/JniHelper'
    vcsUrl = 'https://github.com/Akfz/JniHelper'

    plugins {
        jniHelperPlugin {
            id = 'io.github.Akfz.jnih'
            implementationClass = 'v.akfz.jnih.JniHelperPlugin'
            displayName = 'JNI Helper Plugin'
            description = 'Little helper for Java Native Interface'
            tags.set(['jni', 'native', 'java'])
        }
    }
}